TwitterForZombies/config/routes.rb
Rails.application.routes.draw do
  # math 'zombies/:id/decomp' => "Zombies#decomp", :as => :decomp_zombie
  resources :zombies do
    resources :tweets
    get :decomp, on: :member
    put :custom_decomp, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

TwitterForZombies/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

TwitterForZombies/app/models/brain.rb
class Brain < ApplicationRecord
  belongs_to :zombie 
end

TwitterForZombies/app/models/zombie.rb
class Zombie < ApplicationRecord::Base
  after_save :decomp_change_notification, if :decomp_change?
  
  def as_json(options = nil)
    super(options || {include: :brain, except: [:created_at, :updated_at, :id]})
  end
  private
  def decomp_change_notification
    ZombieMailer.decomp_change(self).deliver
  end
end

TwitterForZombies/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

TwitterForZombies/app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  before_action :set_zombie, only: [:show, :edit, :update, :destroy]

  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
    @zombie = Zombie.find(params[:id])
    # respond_to do |format|
    #   format.html do
    #     if @zombie.decomp == 'Dead (again)' 
    #       render :dead_again
    #     end
    #   end
    #   format.json { render json: @zombie }
    # end
    
    
    # if @zombie.decomp == 'Dead (again)'
    #   render :dead_again
    # end
    
    render json: @zombie
    
  end

  # GET /zombies/new
  def new
    @zombie = Zombie.new
  end

  # GET /zombies/1/edit
  def edit
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(params[:zombie])

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render :show, status: :created, location: @zombie }
      else
        format.html { render :new }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombies/1
  # PATCH/PUT /zombies/1.json
  def update
    respond_to do |format|
      if @zombie.update(zombie_params)
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { render :show, status: :ok, location: @zombie }
      else
        format.html { render :edit }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie = Zombie.find(params[:id])
    @zombie.destroy
    
    respond_to do |format|
      format.html { redirect_to zombies_url }
      format.json { head :ok }
      formt.js
    end
  end
  
  def decomp
    @zombie = Zombie.find(params[:id])
    if @zombie.decomp == 'Dead (again)'
      render json: @zombie.to_json(only: :decomp), status: :unprocessable_entity
    else
      render json: @zombie.to_json(only: :decomp)
    end
  end
  
  def custom_decomp
    @zombie = Zombie.find(params[:id])
    @zombie.decomp = params[:zombie][:decomp]
    @zombie.save
    
    respond_to do |format|
      format.js
      format.json { render json: @zombie.to_json(only :decomp) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zombie
      @zombie = Zombie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zombie_params
      params.require(:zombie).permit(:name, :bio, :age)
    end
end

TwitterForZombies/app/helpers/application_helper.rb
module ApplicationHelper
end

TwitterForZombies/app/helpers/zombies_helper.rb
module ZombiesHelper
end

TwitterForZombies/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterForZombies</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

TwitterForZombies/app/views/zombies/_form.html.erb
<%= form_with(model: zombie, local: true) do |form| %>
  <% if zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% zombie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :zombie_name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :zombie_bio %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :zombie_age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

TwitterForZombies/app/views/zombies/_zombie.html.erb
<%= div_for zombie do %>
  <%= link_to "Zombie #{zombie.name}, zombie" %>
  <div class="actions">
    <%= link_to 'edit', edit_zombie_path(zombie) %>
    <%= link_to 'delete', zombie, method: :delete, remote: true %>
  </div>
<% end %>

TwitterForZombies/app/views/zombies/advanced_decomp.js.erb
$('#decomp').text('<%= @zombie.decomp %>').effect('highlight', {}, 3000);
<% if @zombie.decomp == "Dead (again)!" %>
  $('div#custom_phase').fadeOut();
<% end %>

TwitterForZombies/app/views/zombies/create.js.erb
<% if @zombie.new_record? %>
  $('input#zombie_name').effect('highlight', { color: 'red' });
<% else %>
  $('div#zombies').append("<%= escape_javascript(render @zombie) %>");
  $('div#<%= dom_id(@zombie) %>').effect('highlight');
<% end %>

TwitterForZombies/app/views/zombies/destroy.js.erb
$('#<%= dom_id(@zombie) %>').fadeOut();

TwitterForZombies/app/views/zombies/edit.html.erb
<h1>Editing Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

TwitterForZombies/app/views/zombies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Zombies</h1>
  <div id="zombies">
    <!-- <% @zombies.each do |zombie| %>
      <%= render zombie %>
    <% end %> -->
    
    <%= render @zombies %>
    <%= form_for(Zombie.new, remote: true) do |f| %>
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
<br>

<%= link_to 'New Zombie', new_zombie_path %>

TwitterForZombies/app/views/zombies/new.html.erb
<h1>New Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Back', zombies_path %>

TwitterForZombies/app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zombie.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @zombie.bio %>
</p>

<p>
  <strong>Age:</strong>
  <%= @zombie.age %>
</p>

<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>

<strong>Decomposition Phase:</strong>
<span id="decomp"><%= @zombie.decomp %></span>
<div id="custom_phase">
  <%= form_for @zombie, url: custom_decomp_zombie_path(@zombie), remote: true do |f| %>
    <strong>Custom Phase</strong>
    <%= f.text_field :decomp %>
    <%= f.submit "Set" %>
  <% end %>
</div>


<div id="custom_phase2">
  <%= form_for @zombie, url: custom_decomp_zombie_path(@zombie) do |f| %>
    <strong>Custom Phase via JSON</strong>
    <%= f.text_field :decomp %>
    <%= f.submit "Set" %>
  <% end %>
</div>